// Added (TMAIL-357): Skeleton login/logout handlers for the `/classic` no-JS
// surface.
//
// This file is intentionally a *skeleton* — the real login form rendering,
// password verification, brute-force lockout messaging, and 2FA challenge
// branching land in TMAIL-359 (P0 #5), TMAIL-360 (P0 #6), and TMAIL-361
// (P0 #7) respectively. What lives here today is the contract those tasks
// will hang off:
//
//   * `generate_csrf_token()` — random 32-byte URL-safe base64. The
//     follow-up login handler will call this when creating a session row.
//   * `create_session_and_cookie()` — given a verified mailbox + request
//     metadata, inserts a `classic_sessions` row and returns the signed
//     Set-Cookie header value. Both login (after password check) and SAML
//     callback (when wired) will share this code path.
//   * `destroy_session_and_cookie()` — given a session id, deletes the row
//     and returns the cookie-clearing header value. Logout calls this.
//   * `LOGIN_PATH` / `INBOX_PATH` — symbolic redirect targets so the rest
//     of the Classic UI doesn't have to repeat the string literals.
//
// Wiring: this module is mounted as `pub mod auth` from
// `handlers/classic/mod.rs`. The login/logout *routes* themselves get
// added by the follow-up tasks; we don't pre-register `/classic/login` or
// `/classic/logout` here so a half-implemented form doesn't ship by
// accident.

use axum::http::HeaderValue;
use base64::{engine::general_purpose::URL_SAFE_NO_PAD as B64URL, Engine as _};
use rand::RngCore;
use uuid::Uuid;

use crate::error::AppError;
use crate::middleware::classic_session::{build_clear_cookie_header, build_set_cookie_header};
use crate::models::classic_session::{ClassicSession, CLASSIC_SESSION_TTL_HOURS};
use crate::state::AppState;

#[allow(dead_code)]
pub const LOGIN_PATH: &str = "/classic/login";
#[allow(dead_code)]
pub const INBOX_PATH: &str = "/classic/folders/INBOX";

/// 32 random bytes, URL-safe base64 without padding → 43 visible chars.
/// 256 bits of entropy matches OWASP's CSRF token guidance with headroom.
///
/// Generated by the login handler when it creates a session row, and
/// rendered into every form on the Classic UI as a hidden `_csrf` input.
/// Validation happens in the middleware path (TMAIL-358 P0 #4).
pub fn generate_csrf_token() -> String {
    let mut bytes = [0u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    B64URL.encode(bytes)
}

/// Bundled result of a successful login flow: the inserted row (so the caller
/// can audit-log it) and a ready-to-attach `Set-Cookie` header value.
pub struct EstablishedSession {
    pub session: ClassicSession,
    pub set_cookie: HeaderValue,
}

/// Insert a fresh `classic_sessions` row for the verified user and produce
/// the signed Set-Cookie header that the login handler attaches to its 303
/// response.
///
/// `jwt_secret` is read from `state.config.jwt.secret`. We pass it in as a
/// borrow rather than borrowing `state` fully so that this helper can be
/// called from test contexts that build a config directly.
#[allow(dead_code)]
pub async fn create_session_and_cookie(
    state: &AppState,
    user_id: Uuid,
    ip: Option<&str>,
    ua: Option<&str>,
) -> Result<EstablishedSession, AppError> {
    let csrf = generate_csrf_token();
    let session = ClassicSession::create(&state.db, user_id, &csrf, ip, ua)
        .await
        .map_err(|e| AppError::Internal(anyhow::anyhow!("classic_sessions insert failed: {e}")))?;
    let cookie = build_set_cookie_header(
        &state.config.jwt.secret,
        session.id,
        chrono::Duration::hours(CLASSIC_SESSION_TTL_HOURS).num_seconds(),
    );
    let set_cookie = HeaderValue::from_str(&cookie).map_err(|e| {
        AppError::Internal(anyhow::anyhow!("Set-Cookie header value invalid: {e}"))
    })?;
    Ok(EstablishedSession { session, set_cookie })
}

/// Delete a session row and return the cookie-clearing header. Used by the
/// logout handler (P0 #6) and by the password-change handler (P1 #22).
#[allow(dead_code)]
pub async fn destroy_session_and_cookie(
    state: &AppState,
    session_id: Uuid,
) -> Result<HeaderValue, AppError> {
    let _ = ClassicSession::delete(&state.db, session_id)
        .await
        .map_err(|e| AppError::Internal(anyhow::anyhow!("classic_sessions delete failed: {e}")))?;
    HeaderValue::from_str(&build_clear_cookie_header()).map_err(|e| {
        AppError::Internal(anyhow::anyhow!("clear-cookie header value invalid: {e}"))
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn csrf_token_is_43_chars_url_safe_base64() {
        // 32 raw bytes → URL_SAFE_NO_PAD base64 is ceil(32 * 4 / 3) = 43 chars.
        let t = generate_csrf_token();
        assert_eq!(t.len(), 43, "expected 43-char CSRF token, got {:?}", t);
        for ch in t.chars() {
            assert!(
                ch.is_ascii_alphanumeric() || ch == '-' || ch == '_',
                "non-URL-safe-base64 char {:?} in CSRF token {:?}",
                ch,
                t
            );
        }
    }

    #[test]
    fn csrf_tokens_are_unique() {
        // Defence in depth — a constant CSRF token across sessions defeats
        // its purpose. Generate a batch and confirm uniqueness.
        let mut seen = std::collections::HashSet::new();
        for _ in 0..1_000 {
            assert!(
                seen.insert(generate_csrf_token()),
                "duplicate CSRF token within batch"
            );
        }
    }

    #[test]
    fn redirect_constants_point_under_classic() {
        // Lock the symbolic targets so a rename can't silently send users
        // into the SPA's `/login` instead of `/classic/login`.
        assert!(LOGIN_PATH.starts_with("/classic/"));
        assert!(INBOX_PATH.starts_with("/classic/"));
    }
}
