// Added (TMAIL-357): SQLx model for the `classic_sessions` table.
//
// The /classic no-JS surface uses an HttpOnly cookie that wraps an opaque
// session id. The row in this table is the server-side state that lookup
// resolves to — see `migrations/080_classic_sessions.sql` for the schema
// rationale.
//
// Reading/writing convention:
//   * Look up by `id` (raw pool, bypasses RLS — the middleware needs the row
//     to set up RLS context, so it can't depend on RLS being primed).
//   * `touch()` bumps the sliding-expiry window + last-seen audit fields on
//     each authenticated request.
//   * `delete()` is called by logout; `delete_all_for_user()` by sign-out
//     -everywhere and password change.

use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

/// Sliding-expiry window applied on session create AND on every authenticated
/// hit. Picked to match the gap-analysis acceptance criterion ("24h sliding").
/// Centralised here so the middleware, the create path, and the cleanup sweep
/// all agree on one number.
pub const CLASSIC_SESSION_TTL_HOURS: i64 = 24;

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct ClassicSession {
    pub id: Uuid,
    pub user_id: Uuid,
    pub csrf_token: String,
    pub created_at: DateTime<Utc>,
    pub expires_at: DateTime<Utc>,
    pub last_seen_at: DateTime<Utc>,
    pub last_seen_ip: Option<String>,
    pub last_seen_ua: Option<String>,
}

impl ClassicSession {
    /// Insert a fresh session row. Returns the persisted record so the caller
    /// can read back the server-assigned `id` for the cookie body.
    ///
    /// `csrf_token` is generated by the caller (not this method) because the
    /// raw bytes need to be available to seed both the row AND the response —
    /// generating it here would force a second DB round-trip to retrieve it.
    pub async fn create(
        pool: &sqlx::PgPool,
        user_id: Uuid,
        csrf_token: &str,
        ip: Option<&str>,
        ua: Option<&str>,
    ) -> Result<ClassicSession, sqlx::Error> {
        let expires_at = Utc::now() + Duration::hours(CLASSIC_SESSION_TTL_HOURS);
        sqlx::query_as::<_, ClassicSession>(
            "INSERT INTO classic_sessions
                (id, user_id, csrf_token, created_at, expires_at, last_seen_at, last_seen_ip, last_seen_ua)
             VALUES (gen_random_uuid(), $1, $2, NOW(), $3, NOW(), $4, $5)
             RETURNING *",
        )
        .bind(user_id)
        .bind(csrf_token)
        .bind(expires_at)
        .bind(ip)
        .bind(ua)
        .fetch_one(pool)
        .await
    }

    /// Look up a session by id. Filters out expired rows so a stale cookie
    /// never resolves; the row remains in the table for the cleanup sweep to
    /// reap (cheaper than DELETE-on-miss).
    pub async fn find_active(
        pool: &sqlx::PgPool,
        id: Uuid,
    ) -> Result<Option<ClassicSession>, sqlx::Error> {
        sqlx::query_as::<_, ClassicSession>(
            "SELECT * FROM classic_sessions WHERE id = $1 AND expires_at > NOW()",
        )
        .bind(id)
        .fetch_optional(pool)
        .await
    }

    /// Bump the sliding-expiry window and refresh audit fields on each
    /// authenticated request. Returns the new `expires_at` so the middleware
    /// can decide whether to also re-issue the cookie (it does, with the
    /// same id but a refreshed Max-Age, so the browser's expiry matches the
    /// server's).
    pub async fn touch(
        pool: &sqlx::PgPool,
        id: Uuid,
        ip: Option<&str>,
        ua: Option<&str>,
    ) -> Result<DateTime<Utc>, sqlx::Error> {
        let new_expires = Utc::now() + Duration::hours(CLASSIC_SESSION_TTL_HOURS);
        sqlx::query(
            "UPDATE classic_sessions
                SET expires_at = $2,
                    last_seen_at = NOW(),
                    last_seen_ip = $3,
                    last_seen_ua = $4
              WHERE id = $1",
        )
        .bind(id)
        .bind(new_expires)
        .bind(ip)
        .bind(ua)
        .execute(pool)
        .await?;
        Ok(new_expires)
    }

    pub async fn delete(pool: &sqlx::PgPool, id: Uuid) -> Result<bool, sqlx::Error> {
        let result = sqlx::query("DELETE FROM classic_sessions WHERE id = $1")
            .bind(id)
            .execute(pool)
            .await?;
        Ok(result.rows_affected() > 0)
    }

    /// Used by P1 #23 (sign-out everywhere) and by the password-change handler
    /// when it lands. Returns the count for the audit log.
    #[allow(dead_code)]
    pub async fn delete_all_for_user(
        pool: &sqlx::PgPool,
        user_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let result = sqlx::query("DELETE FROM classic_sessions WHERE user_id = $1")
            .bind(user_id)
            .execute(pool)
            .await?;
        Ok(result.rows_affected())
    }

    /// Added (TMAIL-376): Delete every classic session row for `user_id`
    /// EXCEPT the one whose id matches `keep`. Used by the change-password
    /// handler to revoke every *other* live classic session for the user
    /// without signing the current browser out (the user just successfully
    /// re-authenticated by typing their current password, so logging them
    /// out would be hostile UX).
    ///
    /// Returns the number of rows deleted so the caller can audit-log it.
    /// The `keep` id does not have to actually exist — if the current
    /// request's session row was already cleaned up by another flow, this
    /// reduces to `delete_all_for_user`.
    pub async fn delete_others_for_user(
        pool: &sqlx::PgPool,
        user_id: Uuid,
        keep: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let result = sqlx::query(
            "DELETE FROM classic_sessions WHERE user_id = $1 AND id <> $2",
        )
        .bind(user_id)
        .bind(keep)
        .execute(pool)
        .await?;
        Ok(result.rows_affected())
    }

    /// Background sweep — call from the scheduler tick that already prunes
    /// the JWT `sessions` table (see `services::email_scheduler`).
    #[allow(dead_code)]
    pub async fn cleanup_expired(pool: &sqlx::PgPool) -> Result<u64, sqlx::Error> {
        let result = sqlx::query("DELETE FROM classic_sessions WHERE expires_at < NOW()")
            .execute(pool)
            .await?;
        Ok(result.rows_affected())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ttl_matches_gap_analysis() {
        // The gap analysis (`docs/gap-analysis/classic-ui.md` P0 #3) calls
        // for a 24-hour sliding expiry. Lock the constant down so a future
        // drive-by edit can't quietly tighten the window and surprise beta
        // users with mid-session logouts.
        assert_eq!(CLASSIC_SESSION_TTL_HOURS, 24);
    }
}
