// Added (TMAIL-361): SQLx model for the `pending_2fa_tokens` table.
//
// One-shot per-browser tokens issued by the Classic UI login handler when a
// user with TOTP enrolled has just passed the password check. The /classic
// surface does NOT yet hold a real session — `classic_sessions` rows are
// only created after the 6-digit TOTP code verifies — so this table is the
// "short-lived gate" between password OK and full session.
//
// Convention:
//   * Lookup runs on the raw pool (bypasses RLS) — the 2FA challenge page
//     fires before rls_context_middleware can prime the session, same shape
//     as `classic_sessions::find_active`.
//   * `failed_attempts` is incremented on every wrong code; the handler
//     invalidates the row (DELETE) once it reaches `MAX_FAILED_ATTEMPTS`.
//   * `delete_for_user` lets the login handler clear stale gates for the
//     same user when a fresh password submission lands — keeps the table
//     tidy without waiting for the sweep.

use chrono::{DateTime, Duration, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

/// Pending 2FA challenge lifetime. Fixed (NOT sliding) so a stolen
/// post-password cookie can't be replayed for hours — the user has 5 minutes
/// to type the code or they're sent back to /classic/login.
pub const PENDING_2FA_TTL_SECS: i64 = 300;

/// How many wrong 6-digit codes the user can submit before the pending
/// token is invalidated and they're forced to re-enter their password.
/// Picked to match common webmail UX (Gmail/FastMail accept ~5 wrong codes)
/// while keeping the brute-force window small (5 * 1_000_000 / 5min ≈ 1 in
/// 60k odds of guessing a 6-digit code blindly).
pub const PENDING_2FA_MAX_FAILED_ATTEMPTS: i32 = 5;

#[derive(Debug, Clone, Serialize, Deserialize, FromRow)]
pub struct PendingTwoFactorToken {
    pub id: Uuid,
    pub user_id: Uuid,
    pub csrf_token: String,
    pub failed_attempts: i32,
    pub created_at: DateTime<Utc>,
    pub expires_at: DateTime<Utc>,
    pub last_seen_ip: Option<String>,
    pub last_seen_ua: Option<String>,
}

impl PendingTwoFactorToken {
    /// Insert a fresh pending 2FA row and return the persisted record so the
    /// caller can build the cookie body from the server-assigned `id`.
    ///
    /// `csrf_token` is generated by the caller — same shape as
    /// `ClassicSession::create` — because the raw bytes need to be present
    /// both in the row AND in the rendered form template.
    pub async fn create(
        pool: &sqlx::PgPool,
        user_id: Uuid,
        csrf_token: &str,
        ip: Option<&str>,
        ua: Option<&str>,
    ) -> Result<PendingTwoFactorToken, sqlx::Error> {
        let expires_at = Utc::now() + Duration::seconds(PENDING_2FA_TTL_SECS);
        sqlx::query_as::<_, PendingTwoFactorToken>(
            "INSERT INTO pending_2fa_tokens
                (id, user_id, csrf_token, failed_attempts, created_at, expires_at, last_seen_ip, last_seen_ua)
             VALUES (gen_random_uuid(), $1, $2, 0, NOW(), $3, $4, $5)
             RETURNING *",
        )
        .bind(user_id)
        .bind(csrf_token)
        .bind(expires_at)
        .bind(ip)
        .bind(ua)
        .fetch_one(pool)
        .await
    }

    /// Look up a pending token by id. Filters out expired rows so a stale
    /// cookie never resolves; the row stays in the table for the cleanup
    /// sweep to reap (cheaper than DELETE-on-miss).
    pub async fn find_active(
        pool: &sqlx::PgPool,
        id: Uuid,
    ) -> Result<Option<PendingTwoFactorToken>, sqlx::Error> {
        sqlx::query_as::<_, PendingTwoFactorToken>(
            "SELECT * FROM pending_2fa_tokens WHERE id = $1 AND expires_at > NOW()",
        )
        .bind(id)
        .fetch_optional(pool)
        .await
    }

    /// Increment the failed-attempt counter and return the new value. Used
    /// by the POST handler on every wrong-code submission so it can decide
    /// whether to invalidate the row.
    pub async fn increment_failed(
        pool: &sqlx::PgPool,
        id: Uuid,
    ) -> Result<i32, sqlx::Error> {
        let row: (i32,) = sqlx::query_as(
            "UPDATE pending_2fa_tokens
                SET failed_attempts = failed_attempts + 1
              WHERE id = $1
              RETURNING failed_attempts",
        )
        .bind(id)
        .fetch_one(pool)
        .await?;
        Ok(row.0)
    }

    /// Delete a single pending row. Called after a SUCCESSFUL TOTP verify
    /// (the gate is one-shot) and after `MAX_FAILED_ATTEMPTS` is hit.
    pub async fn delete(pool: &sqlx::PgPool, id: Uuid) -> Result<bool, sqlx::Error> {
        let result = sqlx::query("DELETE FROM pending_2fa_tokens WHERE id = $1")
            .bind(id)
            .execute(pool)
            .await?;
        Ok(result.rows_affected() > 0)
    }

    /// Clear every pending row for a user. Called by the login handler when
    /// a fresh password submission lands — keeps the table from accumulating
    /// stale gates for users that abandon the flow mid-way.
    pub async fn delete_for_user(
        pool: &sqlx::PgPool,
        user_id: Uuid,
    ) -> Result<u64, sqlx::Error> {
        let result = sqlx::query("DELETE FROM pending_2fa_tokens WHERE user_id = $1")
            .bind(user_id)
            .execute(pool)
            .await?;
        Ok(result.rows_affected())
    }

    /// Background sweep — call from the same scheduler tick that prunes
    /// `classic_sessions` and the JWT `sessions` table.
    #[allow(dead_code)]
    pub async fn cleanup_expired(pool: &sqlx::PgPool) -> Result<u64, sqlx::Error> {
        let result = sqlx::query("DELETE FROM pending_2fa_tokens WHERE expires_at < NOW()")
            .execute(pool)
            .await?;
        Ok(result.rows_affected())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ttl_is_five_minutes() {
        // The gap analysis (docs/gap-analysis/classic-ui.md P0 #7) calls for
        // a 5-minute one-shot window. Lock the constant down so a future
        // drive-by edit can't quietly extend the brute-force window.
        assert_eq!(PENDING_2FA_TTL_SECS, 300);
    }

    #[test]
    fn max_failed_attempts_is_five() {
        // Five wrong codes is the upper bound before we force the user back
        // through password re-auth. Locked down so a drive-by tweak can't
        // make the gate brute-forceable.
        assert_eq!(PENDING_2FA_MAX_FAILED_ATTEMPTS, 5);
    }
}
